config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#home'
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/call_for_papers',    to: 'static_pages#call_for_papers',    via: 'get'
  match '/origanization',    to: 'static_pages#origanization',    via: 'get'
  match '/program_committee',    to: 'static_pages#program_committee',    via: 'get'
  match '/program_overview',    to: 'static_pages#program_overview',    via: 'get'
  match '/paper_submission',    to: 'static_pages#paper_submission',    via: 'get'
  match '/important_dates',    to: 'static_pages#important_dates',    via: 'get'
  match '/venue',    to: 'static_pages#venue',    via: 'get'
  match '/post_proceedings',    to: 'static_pages#post_proceedings',    via: 'get'
  match '/futher_information',    to: 'static_pages#futher_information',    via: 'get'
  match '/previous_workshops',    to: 'static_pages#previous_workshops',    via: 'get'
  match '/download_papers',    to: 'static_pages#download_papers',    via: 'get'
  match '/evaluation_campaign',    to: 'static_pages#evaluation_campaign',    via: 'get'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def call_for_papers
	end

	def origanization
	end

	def program_committee
	end

	def program_overview
	end

	def paper_submission
	end

	def post_proceedings
	end

	def important_dates
	end

	def venue
	end

	def futher_information
	end

	def previous_workshops
	end

	def download_papers
	end

	def evaluation_campaign
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer background_color">
	<div style="margin-top: 30px; margin-bottom: 30px; color: rgb(0, 138, 255); text-align: center;">
		<b>The Fourth International Workshop on Vietnamese Language and Speech Processing (VLSP 2016)</b>
	</div>
	
</div>

app/views/layouts/_header.html.erb
<div class="container">
	<div class="background_color" style="border-bottom: none;">
	<%= link_to image_tag("vlsp2016_v1.png"), root_path %>
	<br>
	<br>
	</div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkShop2016</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/shared/_menu.html.erb
<div class="span3"">
	<div>
		<%= link_to "MAIN MENU", root_path, class: "btn btn-large btn-primary", style: "width: 150px; height: 10px; border-bottom-left-radius: 0px; border-bottom-right-radius: 0px;" %>
		<ul class="nav nav-pills nav-stacked">
		<table width="190">
	    	<tr><td><li class="menu_vertical"><%= link_to "Home", home_path %> </li></td></tr>
			<tr><td><li class="menu_vertical"><%= link_to "Call for Papers", call_for_papers_path %> </li></td></tr>
			<!-- <tr><td><li class="menu_vertical"><%#= link_to "Organization", origanization_path %> </li></td></tr> -->
			<tr><td><li class="menu_vertical"><%= link_to "Program Committee", program_committee_path %> </li></td></tr>
			<tr><td><li class="menu_vertical"><%= link_to "Evaluation Campaign", evaluation_campaign_path %> </li></td></tr>
			<tr><td><li class="menu_vertical"><%= link_to "Workshop Program", program_overview_path %> </li></td></tr>
			<tr><td><li class="menu_vertical"><%= link_to "Paper Submission", paper_submission_path %> </li></td></tr>
			<tr><td><li class="menu_vertical"><%= link_to "Post Proceedings", post_proceedings_path %> </li></td></tr>
			<tr><td><li class="menu_vertical"><%= link_to "Important Dates", important_dates_path %> </li></td></tr>
			<tr><td><li class="menu_vertical"><%= link_to "Venue", venue_path %> </li></td></tr>
			<!-- <tr><td><li class="menu_vertical"><%#= link_to "Further Information", futher_information_path %> </li></td></tr> -->
			<tr><td><li class="menu_vertical"><%= link_to "Previous Workshops", previous_workshops_path %> </li></td></tr>
			<tr><td><li class="menu_vertical"><%= link_to "Download Papers", download_papers_path %> </li></td></tr>
		</table>
	  	</ul>
	</div>
</div>

app/views/static_pages/call_for_papers.html.erb
<div class="background_color" style="border-top: none;">
	<div class="row">
		<%= render partial: "shared/menu" %>
		<div class="span9 content">
			<div class="title_page">
				<p><b>Call for papers</b></p>
				<p>The Fourth International Workshop on Vietnamese Language and Speech Processing (VLSP 2016)</p>
			</div>
			<div style="text-align: center;word-wrap: break-word; margin-left: 100px; width: 480px;">
				<p><b>In conjunction with the 12th IEEE - RIVF Conference on Computing and Communication Technologies (RIVF 2016)</b></p>
			</div>
			<div>
			<br>
<p><b>Workshop objectives:</b></p>
<p>The goal of this workshop series is to attempt a synthesis of research in Vietnamese language and speech processing and to bring together researchers and professionals working in this domain. The VLSP 2016 edition will be composed of two parts: one part for VLSP software demonstration with technical reports, and an evaluation campaign on the tasks of named-entity recognition and opinion mining. As is traditional, one panel for the VLSP community exchange and discussion will be organized. </p>

<p><b>Software demonstration</b></p>

<p>All applications dealing with Vietnamese text processing or speech processing are welcome. Each demo system should be provided with a technical report.</p>

<p><b>Evaluation campaign</b></p>

<p>The evaluation campaign deals with two different tasks. One concerns named-entity recognition (NER), an essential task for information extraction applications. The evaluation will be limited in considering 3 types of entity: person, organization and location. The other concerns an opinion mining (OM) tool at sentence level, in which each given sentence should be classified as negative, positive or neutral. </p>
<p>The participants to the evaluation campaign will be asked to present their system in a dedicated short paper.</p>
<p>This campaign aims at automatically evaluating Vietnamese NER and OM systems, in order to promote the most efficient methods for these important tools. The organization of this campaign with sponsor from academia and industry will permit to build and offer to the VLSP community gold datasets for training and testing NER and OM systems. <p>

<p><b>Paper submission:</b></p>

<p>System authors are invited to submit papers of up to 8 pages, in English. Please note that this workshop is only concerned with articles presenting software submitted for demonstration or evaluation. All papers will be submitted online, in PDF format using the IEEE standard template, to the workshop management website.</p>

<p><b>Important dates:</b></p>

<p>June 30, 2016:            Sample data and evaluation measure publication   </p>

<p>July 5, 2016:               Registration to the campaign</p>

<p>August 30, 2016:        Distribution of training data for NER and OM tasks</p>

<p>September 5, 2016:    Registration to the campaign closed</p>

<p>October 3, 2016:         Test data release</p>

<p>October 7, 2016:         System result submission</p>

<p>October 9, 2016:         Demonstration system and technical report submission deadline</p>

<p>October 28, 2016:       Registration to the workshop deadline</p>

<p>November 7, 2016:    Workshop</p>

<p><b>Workshop Co-chairs:</b></p>

<p>Le Anh Cuong, Ton Duc Thang University, Ho Chi Minh city, Vietnam, lacuong@it.tdt.edu.vn</p>

<p>Nguyen Thi Minh Huyen, VNU University of Science, Hanoi, Vietnam, huyenntm@hus.edu.vn</p>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/download_papers.html.erb
<div class="background_color"  style="border-top: none;">
	<div class="row">
		<%= render partial: "shared/menu" %>
		<div class="span9 content">
			<div class="title_page">
				<p><b>Download papers</b></p>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/evaluation_campaign.html.erb
<div class="background_color" style="border-top: none;">
	<div class="row">
		<%= render partial: "shared/menu" %>
		<div class="span9 content">
			<div class="title_page">
				
				<p><b>Evaluation campaign</b></p>
			</div>
			
			<div>
			

<p><b>Evaluation campaign</b></p>

<p>The evaluation campaign deals with two different tasks. One concerns named-entity recognition (NER), an essential task for information extraction applications. The evaluation will be limited in considering 3 types of entity: person, organization and location. The other concerns an opinion mining (OM) tool at sentence level, in which each given sentence should be classified as negative, positive or neutral. </p>
<p>The participants to the evaluation campaign will be asked to present their system in a dedicated short paper.</p>
<p>This campaign aims at automatically evaluating Vietnamese NER and OM systems, in order to promote the most efficient methods for these important tools. The organization of this campaign with sponsor from academia and industry will permit to build and offer to the VLSP community gold datasets for training and testing NER and OM systems. <p>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/futher_information.html.erb
<div class="background_color" style="border-top: none;">
	<div class="row">
		<%= render partial: "shared/menu" %>
		<div class="span9 content">
			<div class="title_page">
				futher information
			</div>
			futher information content
		</div>
	</div>
</div>

app/views/static_pages/home.html.erb
<div class="background_color" style="border-top: none;">
	<div class="row">
		<%= render partial: "shared/menu" %>
		<div class="span9 content">
			<div class="title_page">
				
				<p>The Fourth International Workshop on Vietnamese Language and Speech Processing (VLSP 2016)</p>
			</div>
			<div style="text-align: center;word-wrap: break-word; margin-left: 100px; width: 480px;">
				<p><b>In conjunction with the 12th IEEE - RIVF Conference on Computing and Communication Technologies (RIVF 2016)</b></p>
			</div>
			<div>
			<br>
				<p><b>Workshop objectives:</b></p>

<p>The goal of this workshop series is to attempt a synthesis of research in Vietnamese language and speech processing and to bring together researchers and professionals working in this domain. The VLSP 2016 edition will be composed of two parts: one part for VLSP software demonstration with technical reports, and an evaluation campaign on the tasks of named-entity recognition and opinion mining. As is traditional, one panel for the VLSP community exchange and discussion will be organized. </p>

<p><b>Software demonstration</b></p>

<p>All applications dealing with Vietnamese text processing or speech processing are welcome. Each demo system should be provided with a technical report.</p>

<p><b>Evaluation campaign</b></p>

<p>The evaluation campaign deals with two different tasks. One concerns named-entity recognition (NER), an essential task for information extraction applications. The evaluation will be limited in considering 3 types of entity: person, organization and location. The other concerns an opinion mining (OM) tool at sentence level, in which each given sentence should be classified as negative, positive or neutral. </p>
<p>The participants to the evaluation campaign will be asked to present their system in a dedicated short paper.</p>
<p>This campaign aims at automatically evaluating Vietnamese NER and OM systems, in order to promote the most efficient methods for these important tools. The organization of this campaign with sponsor from academia and industry will permit to build and offer to the VLSP community gold datasets for training and testing NER and OM systems. <p>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/important_dates.html.erb
<div class="background_color" style="border-top: none;">
	<div class="row">
		<%= render partial: "shared/menu" %>
		<div class="span9 content">
			<div class="title_page">
				<p><b>impotant dates</b></p>
			</div>
			<div>
				<p><b>Important dates:</b></p>

<p>June 30, 2016:            Sample data and evaluation measure publication   </p>

<p>July 5, 2016:               Registration to the campaign</p>

<p>August 30, 2016:        Distribution of training data for NER and OM tasks</p>

<p>September 5, 2016:    Registration to the campaign closed</p>

<p>October 3, 2016:         Test data release</p>

<p>October 7, 2016:         System result submission</p>

<p>October 9, 2016:         Demonstration system and technical report submission deadline</p>

<p>October 28, 2016:       Registration to the workshop deadline</p>

<p>November 7, 2016:    Workshop</p>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/origanization.html.erb
<div class="background_color" style="border-top: none;">
	<div class="row">
		<%= render partial: "shared/menu" %>
		<div class="span8 content">
			<div class="title_page">
				origanization
			</div>
			origanization content
		</div>
	</div>
</div>

app/views/static_pages/paper_submission.html.erb
<div class="background_color" style="border-top: none;">
	<div class="row">
		<%= render partial: "shared/menu" %>
		<div class="span9 content">
			<div class="title_page">
				<p><b>Paper submission</b></p>
			</div>
			<div>
				<p><b>Paper submission:</b></p>

<p>System authors are invited to submit papers of up to 8 pages, in English. Please note that this workshop is only concerned with articles presenting software submitted for demonstration or evaluation. All papers will be submitted online, in PDF format using the IEEE standard template, to the workshop management website.</p>
<%= link_to "http://www.ieee.org/conferences_events/conferences/publishing/templates.html", "http://www.ieee.org/conferences_events/conferences/publishing/templates.html", target: "_blank" %>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/post_proceedings.html.erb
<div class="background_color" style="border-top: none;">
	<div class="row">
		<%= render partial: "shared/menu" %>
		<div class="span9 content">
			<div class="title_page">
				<p><b>Post proceedings</b></p>
			</div>
			<div>
				
			</div>
		</div>
	</div>
</div>

app/views/static_pages/previous_workshops.html.erb
<div class="background_color" style="border-top: none;">
	<div class="row">
		<%= render partial: "shared/menu" %>
		<div class="span9 content">
			<div class="title_page">
				<p><b>Previous workshops</b></p>
			</div>
			<div>
				
			</div>
		</div>
	</div>
</div>

app/views/static_pages/program_committee.html.erb
<div class="background_color" style="border-top: none;">
	<div class="row">
		<%= render partial: "shared/menu" %>
		<div class="span9 content">
			<div class="title_page">
				<p><b>Program committee</b></p>
			</div>
			<div>
<p><b>Workshop Co-chairs:</b></p>

<p>Le Anh Cuong, Ton Duc Thang University, Ho Chi Minh city, Vietnam, lacuong@it.tdt.edu.vn</p>

<p>Nguyen Thi Minh Huyen, VNU University of Science, Hanoi, Vietnam, huyenntm@hus.edu.vn</p>
<p><b>Program Committee (to be completed):</b></p>
<p>1.      Dinh Dien, University of Science, VNU-HCM, Vietnam (co-chair)</p>
<p>2.      Luong Chi Mai, Institute of Information Technology, VAST, Vietnam (co-chair)</p>
<p>3.      Cao Hoang Tru, University of Technology, VNU-HCM, Vietnam</p>
<p>4.      Ho Bao Quoc, University of Science, VNU-HCM, Vietnam</p>
<p>5.      Ho Tu Bao, JAIST, Japan</p>
<p>6.      Le Anh Cuong, Ton Duc Thang University, Ho Chi Minh city, Vietnam</p>
<p>7.      Le Hong Phuong, University of Science, VNU, Hanoi, Vietnam</p>
<p>8.      Le Thanh Huong, Hanoi University of Science and Technology, Vietnam</p>
<p>9.      Ngo Xuan Bach, Posts and Telecommunications Institute of Technology, Hanoi, Vietnam</p>
<p>10.    Nguyen Le Minh, JAIST, Japan</p>
<p>11.    Nguyen Phuong Thai, University of Engineering and Technology, VNU, Hanoi, Vietnam</p>
<p>12.    Nguyen Thi Minh Huyen, University of Science, VNU, Hanoi, Vietnam</p>
<p>13.    Nguyen Van Vinh, University of Engineering and Technology, VNU, Hanoi, Vietnam</p>
<p>14.    Nguyen Viet Cuong, HPC Systems, Inc., Japan</p>
<p>15.    Nguyen Viet Son, Hanoi University of Science and Technology, Vietnam</p>
<p>16.    Pham Bao Son, University of Engineering and Technology, VNU, Hanoi, Vietnam</p>
<p>17.    Phan Thi Tuoi, University of Technology, VNU-HCM, Vietnam</p>
<p>18.    Phan Xuan Hieu, University of Engineering and Technology, VNU, Hanoi, Vietnam</p>
<p>19.    Tran Do Dat, Ministry of Science and Technology, Vietnam</p>
<p>20.    Vu Hai Quan, University of Science, VNU-HCM, Vietnam</p>
<p>21.    Vu Tat Thang, Institute of Information Technology, VAST, Vietnam</p>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/program_overview.html.erb
<div class="background_color" style="border-top: none;">
	<div class="row">
		<%= render partial: "shared/menu" %>
		<div class="span9 content">
			<div class="title_page">
				<p><b>Workshop program<b></p>
			</div>
			
		</div>
	</div>
</div>

app/views/static_pages/venue.html.erb
<div class="background_color" style="border-top: none;">
	<div class="row">
		<%= render partial: "shared/menu" %>
		<div class="span9 content">
			<div class="title_page">
				<p><b>Venue</b></p>
			</div>
			<div>
				<p>The VLSP 2016 workshop is organized in conjunction with the RIVF 2016 conference. Please find all the information related to the conference site on the main <%= link_to "conference website.", "http://rivf2016.tlu.edu.vn/tabid/394/catid/947/local-information.aspx", target: "_blank" %> </p>
			</div>
			
		</div>
	</div>
</div>